#pragma once

#include <ntddk.h>

#define VDM_DEVICE_TYPE 0x8010
#define VDM_IOCTL_VERSION 1

#define IOCTL_VDM_GET_HEALTH CTL_CODE(VDM_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_VDM_CREATE_PAIR CTL_CODE(VDM_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_VDM_DELETE_PAIR CTL_CODE(VDM_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_WRITE_DATA)

typedef struct _VDM_PAIR_REQUEST
{
    ULONG Version;
    WCHAR TxPort[16];
    WCHAR RxPort[16];
} VDM_PAIR_REQUEST, *PVDM_PAIR_REQUEST;

typedef struct _VDM_OPERATION_RESPONSE
{
    ULONG Version;
    NTSTATUS Status;
    ULONG PairCount;
} VDM_OPERATION_RESPONSE, *PVDM_OPERATION_RESPONSE;
